### ISSUE TITLE
No typescript version

### ISSUE THREAD

**Issue by pitchart** [les-tontons-crafters/submarine-submarine-tcr-autumn-camp#2]
Hello les tontons.

It's a shame, this wonderfull repository doesn't provide a typescript version.

Good news, I'm working on it so a PR will pop soon if you are opened for it :)

Just a question : I need to upgrade the TCR tool version to provide configuration for typescript. 
Should I make a dedicated PR for it ?

**Comment by ythirion** [comment]
Hi Julien, thanks for the proposal.
Of course, a typescript version is more than welcome 🤗 

Just an answer 😉 : for me you can update TCR in the same PR.
